const mongoose = require('mongoose');
require('dotenv').config();
const Hymn = require('./models/Hymn');

const hymns = [
    // Restoration
    { number: 1, title: "The Morning Breaks", category: "Restoration" },
    { number: 2, title: "The Spirit of God", category: "Restoration" },
    { number: 3, title: "Now Let Us Rejoice", category: "Restoration" },
    { number: 4, title: "Truth Eternal", category: "Restoration" },
    { number: 5, title: "High on the Mountain Top", category: "Restoration" },
    { number: 6, title: "Redeemer of Israel", category: "Restoration" },
    { number: 7, title: "Israel, Israel, God Is Calling", category: "Restoration" },
    { number: 8, title: "Awake and Arise", category: "Restoration" },
    { number: 9, title: "Come, Rejoice", category: "Restoration" },
    { number: 10, title: "Come, Sing to the Lord", category: "Restoration" },
    { number: 11, title: "What Was Witnessed in the Heavens?", category: "Restoration" },
    { number: 12, title: "'Twas Witnessed in the Morning Sky", category: "Restoration" },
    { number: 13, title: "An Angel from on High", category: "Restoration" },
    { number: 14, title: "Sweet Is the Peace the Gospel Brings", category: "Restoration" },
    { number: 15, title: "I Saw a Mighty Angel Fly", category: "Restoration" },
    { number: 16, title: "What Glorious Scenes Mine Eyes Behold", category: "Restoration" },
    { number: 17, title: "Awake, Ye Saints of God, Awake!", category: "Restoration" },
    { number: 18, title: "The Voice of God Again Is Heard", category: "Restoration" },
    { number: 19, title: "We Thank Thee, O God, for a Prophet", category: "Restoration" },
    { number: 20, title: "God of Power, God of Right", category: "Restoration" },
    { number: 21, title: "Come, Listen to a Prophet's Voice", category: "Restoration" },
    { number: 22, title: "We Listen to a Prophet's Voice", category: "Restoration" },
    { number: 23, title: "We Ever Pray for Thee", category: "Restoration" },
    { number: 24, title: "God Bless Our Prophet Dear", category: "Restoration" },
    { number: 25, title: "Now We'll Sing with One Accord", category: "Restoration" },
    { number: 26, title: "Joseph Smith's First Prayer", category: "Restoration" },
    { number: 27, title: "Praise to the Man", category: "Restoration" },
    { number: 28, title: "Saints, Behold How Great Jehovah", category: "Restoration" },
    { number: 29, title: "A Poor Wayfaring Man of Grief", category: "Restoration" },
    { number: 30, title: "Come, Come, Ye Saints", category: "Restoration" },
    { number: 31, title: "O God, Our Help in Ages Past", category: "Restoration" },
    { number: 32, title: "The Happy Day at Last Has Come", category: "Restoration" },
    { number: 33, title: "Our Mountain Home So Dear", category: "Restoration" },
    { number: 34, title: "O Ye Mountains High", category: "Restoration" },
    { number: 35, title: "For the Strength of the Hills", category: "Restoration" },
    { number: 36, title: "They, the Builders of the Nation", category: "Restoration" },
    { number: 37, title: "The Wintry Day, Descending to Its Close", category: "Restoration" },
    { number: 38, title: "Come, All Ye Saints of Zion", category: "Restoration" },
    { number: 39, title: "O Saints of Zion", category: "Restoration" },
    { number: 40, title: "Arise, O Glorious Zion", category: "Restoration" },
    { number: 41, title: "Let Zion in Her Beauty Rise", category: "Restoration" },
    { number: 42, title: "Hail to the Brightness of Zion's Glad Morning!", category: "Restoration" },
    { number: 43, title: "Zion Stands with Hills Surrounded", category: "Restoration" },
    { number: 44, title: "Beautiful Zion, Built Above", category: "Restoration" },
    { number: 45, title: "Lead Me into Life Eternal", category: "Restoration" },
    { number: 46, title: "Glorious Things of Thee Are Spoken", category: "Restoration" },
    { number: 47, title: "We Will Sing of Zion", category: "Restoration" },
    { number: 48, title: "Glorious Things Are Sung of Zion", category: "Restoration" },
    { number: 49, title: "Adam-ondi-Ahman", category: "Restoration" },
    { number: 50, title: "Come, Thou Glorious Day of Promise", category: "Restoration" },
    { number: 51, title: "Sons of Michael, He Approaches", category: "Restoration" },
    { number: 52, title: "The Day Dawn Is Breaking", category: "Restoration" },
    { number: 53, title: "Let Earth's Inhabitants Rejoice", category: "Restoration" },
    { number: 54, title: "Behold, the Mountain of the Lord", category: "Restoration" },
    { number: 55, title: "Lo, the Mighty God Appearing!", category: "Restoration" },
    { number: 56, title: "Softly Beams the Sacred Dawning", category: "Restoration" },
    { number: 57, title: "We're Not Ashamed to Own Our Lord", category: "Restoration" },
    { number: 58, title: "Come, Ye Children of the Lord", category: "Restoration" },
    { number: 59, title: "Come, O Thou King of Kings", category: "Restoration" },
    { number: 60, title: "Battle Hymn of the Republic", category: "Restoration" },
    { number: 61, title: "Raise Your Voices to the Lord", category: "Restoration" },

    // Praise and Thanksgiving
    { number: 62, title: "All Creatures of Our God and King", category: "Praise and Thanksgiving" },
    { number: 63, title: "Great King of Heaven", category: "Praise and Thanksgiving" },
    { number: 64, title: "On This Day of Joy and Gladness", category: "Praise and Thanksgiving" },
    { number: 65, title: "Come, All Ye Saints Who Dwell on Earth", category: "Praise and Thanksgiving" },
    { number: 66, title: "Rejoice, the Lord Is King!", category: "Praise and Thanksgiving" },
    { number: 67, title: "Glory to God on High", category: "Praise and Thanksgiving" },
    { number: 68, title: "A Mighty Fortress Is Our God", category: "Praise and Thanksgiving" },
    { number: 69, title: "All Glory, Laud, and Honor", category: "Praise and Thanksgiving" },
    { number: 70, title: "Sing Praise to Him", category: "Praise and Thanksgiving" },
    { number: 71, title: "With Songs of Praise", category: "Praise and Thanksgiving" },
    { number: 72, title: "Praise to the Lord, the Almighty", category: "Praise and Thanksgiving" },
    { number: 73, title: "Praise the Lord with Heart and Voice", category: "Praise and Thanksgiving" },
    { number: 74, title: "Praise Ye the Lord", category: "Praise and Thanksgiving" },
    { number: 75, title: "In Hymns of Praise", category: "Praise and Thanksgiving" },
    { number: 76, title: "God of Our Fathers, We Come unto Thee", category: "Praise and Thanksgiving" },
    { number: 77, title: "Great Is the Lord", category: "Praise and Thanksgiving" },
    { number: 78, title: "God of Our Fathers, Whose Almighty Hand", category: "Praise and Thanksgiving" },
    { number: 79, title: "With All the Power of Heart and Tongue", category: "Praise and Thanksgiving" },
    { number: 80, title: "God of Our Fathers, Known of Old", category: "Praise and Thanksgiving" },
    { number: 81, title: "Press Forward, Saints", category: "Praise and Thanksgiving" },
    { number: 82, title: "For All the Saints", category: "Praise and Thanksgiving" },
    { number: 83, title: "Guide Us, O Thou Great Jehovah", category: "Praise and Thanksgiving" },
    { number: 84, title: "Faith of Our Fathers", category: "Praise and Thanksgiving" },
    { number: 85, title: "How Firm a Foundation", category: "Praise and Thanksgiving" },
    { number: 86, title: "How Great Thou Art", category: "Praise and Thanksgiving" },
    { number: 87, title: "God Is Love", category: "Praise and Thanksgiving" },
    { number: 88, title: "Great God, Attend While Zion Sings", category: "Praise and Thanksgiving" },
    { number: 89, title: "The Lord Is My Light", category: "Praise and Thanksgiving" },
    { number: 90, title: "From All That Dwell below the Skies", category: "Praise and Thanksgiving" },
    { number: 91, title: "Father, Thy Children to Thee Now Raise", category: "Praise and Thanksgiving" },
    { number: 92, title: "For the Beauty of the Earth", category: "Praise and Thanksgiving" },
    { number: 93, title: "Prayer of Thanksgiving", category: "Praise and Thanksgiving" },
    { number: 94, title: "Come, Ye Thankful People", category: "Praise and Thanksgiving" },
    { number: 95, title: "Now Thank We All Our God", category: "Praise and Thanksgiving" },
    { number: 96, title: "Dearest Children, God Is Near You", category: "Praise and Thanksgiving" },

    // Prayer and Supplication
    { number: 97, title: "Lead, Kindly Light", category: "Prayer and Supplication" },
    { number: 98, title: "I Need Thee Every Hour", category: "Prayer and Supplication" },
    { number: 99, title: "Nearer, Dear Savior, to Thee", category: "Prayer and Supplication" },
    { number: 100, title: "Nearer, My God, to Thee", category: "Prayer and Supplication" },
    { number: 101, title: "Guide Me to Thee", category: "Prayer and Supplication" },
    { number: 102, title: "Jesus, Lover of My Soul", category: "Prayer and Supplication" },
    { number: 103, title: "Precious Savior, Dear Redeemer", category: "Prayer and Supplication" },
    { number: 104, title: "Jesus, Savior, Pilot Me", category: "Prayer and Supplication" },
    { number: 105, title: "Master, the Tempest Is Raging", category: "Prayer and Supplication" },
    { number: 106, title: "God Speed the Right", category: "Prayer and Supplication" },
    { number: 107, title: "Lord, Accept Our True Devotion", category: "Prayer and Supplication" },
    { number: 108, title: "The Lord Is My Shepherd", category: "Prayer and Supplication" },
    { number: 109, title: "The Lord My Pasture Will Prepare", category: "Prayer and Supplication" },
    { number: 110, title: "Cast Thy Burden upon the Lord", category: "Prayer and Supplication" },
    { number: 111, title: "Rock of Ages", category: "Prayer and Supplication" },
    { number: 112, title: "Savior, Redeemer of My Soul", category: "Prayer and Supplication" },
    { number: 113, title: "Our Savior's Love", category: "Prayer and Supplication" },
    { number: 114, title: "Come unto Him", category: "Prayer and Supplication" },
    { number: 115, title: "Come, Ye Disconsolate", category: "Prayer and Supplication" },
    { number: 116, title: "Come, Follow Me", category: "Prayer and Supplication" },
    { number: 117, title: "Come unto Jesus", category: "Prayer and Supplication" },
    { number: 118, title: "Ye Simple Souls Who Stray", category: "Prayer and Supplication" },
    { number: 119, title: "Come, We That Love the Lord", category: "Prayer and Supplication" },
    { number: 120, title: "Lean on My Ample Arm", category: "Prayer and Supplication" },
    { number: 121, title: "I'm a Pilgrim, I'm a Stranger", category: "Prayer and Supplication" },
    { number: 122, title: "Though Deepening Trials", category: "Prayer and Supplication" },
    { number: 123, title: "Oh, May My Soul Commune with Thee", category: "Prayer and Supplication" },
    { number: 124, title: "Be Still, My Soul", category: "Prayer and Supplication" },
    { number: 125, title: "How Gentle God's Commands", category: "Prayer and Supplication" },
    { number: 126, title: "How Long, O Lord Most Holy and True", category: "Prayer and Supplication" },
    { number: 127, title: "Does the Journey Seem Long?", category: "Prayer and Supplication" },
    { number: 128, title: "When Faith Endures", category: "Prayer and Supplication" },
    { number: 129, title: "Where Can I Turn for Peace?", category: "Prayer and Supplication" },
    { number: 130, title: "Be Thou Humble", category: "Prayer and Supplication" },
    { number: 131, title: "More Holiness Give Me", category: "Prayer and Supplication" },
    { number: 132, title: "God Is in His Holy Temple", category: "Prayer and Supplication" },
    { number: 133, title: "Father in Heaven", category: "Prayer and Supplication" },
    { number: 134, title: "I Believe in Christ", category: "Prayer and Supplication" },
    { number: 135, title: "My Redeemer Lives", category: "Prayer and Supplication" },
    { number: 136, title: "I Know That My Redeemer Lives", category: "Prayer and Supplication" },
    { number: 137, title: "Testimony", category: "Prayer and Supplication" },
    { number: 138, title: "Bless Our Fast, We Pray", category: "Prayer and Supplication" },
    { number: 139, title: "In Fasting We Approach Thee", category: "Prayer and Supplication" },
    { number: 140, title: "Did You Think to Pray?", category: "Prayer and Supplication" },
    { number: 141, title: "Jesus, the Very Thought of Thee", category: "Prayer and Supplication" },
    { number: 142, title: "Sweet Hour of Prayer", category: "Prayer and Supplication" },
    { number: 143, title: "Let the Holy Spirit Guide", category: "Prayer and Supplication" },
    { number: 144, title: "Secret Prayer", category: "Prayer and Supplication" },
    { number: 145, title: "Prayer Is the Soul's Sincere Desire", category: "Prayer and Supplication" },
    { number: 146, title: "Gently Raise the Sacred Strain", category: "Prayer and Supplication" },
    { number: 147, title: "Sweet Is the Work", category: "Prayer and Supplication" },
    { number: 148, title: "Sabbath Day", category: "Prayer and Supplication" },
    { number: 149, title: "As the Dew from Heaven Distilling", category: "Prayer and Supplication" },
    { number: 150, title: "O Thou Kind and Gracious Father", category: "Prayer and Supplication" },
    { number: 151, title: "We Meet, Dear Lord", category: "Prayer and Supplication" },
    { number: 152, title: "God Be with You Till We Meet Again", category: "Prayer and Supplication" },
    { number: 153, title: "Lord, We Ask Thee Ere We Part", category: "Prayer and Supplication" },
    { number: 154, title: "Father, This Hour Has Been One of Joy", category: "Prayer and Supplication" },
    { number: 155, title: "We Have Partaken of Thy Love", category: "Prayer and Supplication" },
    { number: 156, title: "Sing We Now at Parting", category: "Prayer and Supplication" },
    { number: 157, title: "Thy Spirit, Lord, Has Stirred Our Souls", category: "Prayer and Supplication" },
    { number: 158, title: "Before Thee, Lord, I Bow My Head", category: "Prayer and Supplication" },
    { number: 159, title: "Now the Day Is Over", category: "Prayer and Supplication" },
    { number: 160, title: "Softly Now the Light of Day", category: "Prayer and Supplication" },
    { number: 161, title: "The Lord Be with Us", category: "Prayer and Supplication" },
    { number: 162, title: "Lord, We Come before Thee Now", category: "Prayer and Supplication" },
    { number: 163, title: "Lord, Dismiss Us with Thy Blessing", category: "Prayer and Supplication" },
    { number: 164, title: "Great God, to Thee My Evening Song", category: "Prayer and Supplication" },
    { number: 165, title: "Abide with Me; 'Tis Eventide", category: "Prayer and Supplication" },
    { number: 166, title: "Abide with Me!", category: "Prayer and Supplication" },
    { number: 167, title: "Come, Let Us Sing an Evening Hymn", category: "Prayer and Supplication" },
    { number: 168, title: "As the Shadows Fall", category: "Prayer and Supplication" },

    // Sacrament
    { number: 169, title: "As Now We Take the Sacrament", category: "Sacrament" },
    { number: 170, title: "God, Our Father, Hear Us Pray", category: "Sacrament" },
    { number: 171, title: "With Humble Heart", category: "Sacrament" },
    { number: 172, title: "In Humility, Our Savior", category: "Sacrament" },
    { number: 173, title: "While of These Emblems We Partake", category: "Sacrament" },
    { number: 174, title: "While of These Emblems We Partake", category: "Sacrament" },
    { number: 175, title: "O God, the Eternal Father", category: "Sacrament" },
    { number: 176, title: "'Tis Sweet to Sing the Matchless Love", category: "Sacrament" },
    { number: 177, title: "'Tis Sweet to Sing the Matchless Love", category: "Sacrament" },
    { number: 178, title: "O Lord of Hosts", category: "Sacrament" },
    { number: 179, title: "Again, Our Dear Redeeming Lord", category: "Sacrament" },
    { number: 180, title: "Father in Heaven, We Do Believe", category: "Sacrament" },
    { number: 181, title: "Jesus of Nazareth, Savior and King", category: "Sacrament" },
    { number: 182, title: "We'll Sing All Hail to Jesus' Name", category: "Sacrament" },
    { number: 183, title: "In Remembrance of Thy Suffering", category: "Sacrament" },
    { number: 184, title: "Upon the Cross of Calvary", category: "Sacrament" },
    { number: 185, title: "Reverently and Meekly Now", category: "Sacrament" },
    { number: 186, title: "Again We Meet around the Board", category: "Sacrament" },
    { number: 187, title: "God Loved Us, So He Sent His Son", category: "Sacrament" },
    { number: 188, title: "Thy Will, O Lord, Be Done", category: "Sacrament" },
    { number: 189, title: "O Thou, Before the World Began", category: "Sacrament" },
    { number: 190, title: "In Memory of the Crucified", category: "Sacrament" },
    { number: 191, title: "Behold the Great Redeemer Die", category: "Sacrament" },
    { number: 192, title: "He Died! The Great Redeemer Died", category: "Sacrament" },
    { number: 193, title: "I Stand All Amazed", category: "Sacrament" },
    { number: 194, title: "There Is a Green Hill Far Away", category: "Sacrament" },
    { number: 195, title: "How Great the Wisdom and the Love", category: "Sacrament" },
    { number: 196, title: "Jesus, Once of Humble Birth", category: "Sacrament" },

    // Easter
    { number: 197, title: "O Savior, Thou Who Wearest a Crown", category: "Easter" },
    { number: 198, title: "That Easter Morn", category: "Easter" },
    { number: 199, title: "He Is Risen!", category: "Easter" },
    { number: 200, title: "Christ the Lord Is Risen Today", category: "Easter" },

    // Christmas
    { number: 201, title: "Joy to the World", category: "Christmas" },
    { number: 202, title: "Oh, Come, All Ye Faithful", category: "Christmas" },
    { number: 203, title: "Angels We Have Heard on High", category: "Christmas" },
    { number: 204, title: "Silent Night", category: "Christmas" },
    { number: 205, title: "Once in Royal David's City", category: "Christmas" },
    { number: 206, title: "Away in a Manger", category: "Christmas" },
    { number: 207, title: "It Came upon the Midnight Clear", category: "Christmas" },
    { number: 208, title: "O Little Town of Bethlehem", category: "Christmas" },
    { number: 209, title: "Hark! The Herald Angels Sing", category: "Christmas" },
    { number: 210, title: "With Wondering Awe", category: "Christmas" },
    { number: 211, title: "While Shepherds Watched Their Flocks", category: "Christmas" },
    { number: 212, title: "Far, Far Away on Judea's Plains", category: "Christmas" },
    { number: 213, title: "The First Noel", category: "Christmas" },
    { number: 214, title: "I Heard the Bells on Christmas Day", category: "Christmas" },

    // Special Topics
    { number: 215, title: "Ring Out, Wild Bells", category: "Special Topics" },
    { number: 216, title: "We Are Sowing", category: "Special Topics" },
    { number: 217, title: "Come, Let Us Anew", category: "Special Topics" },
    { number: 218, title: "We Give Thee But Thine Own", category: "Special Topics" },
    { number: 219, title: "Because I Have Been Given Much", category: "Special Topics" },
    { number: 220, title: "Lord, I Would Follow Thee", category: "Special Topics" },
    { number: 221, title: "Dear to the Heart of the Shepherd", category: "Special Topics" },
    { number: 222, title: "Hear Thou Our Hymn, O Lord", category: "Special Topics" },
    { number: 223, title: "Have I Done Any Good?", category: "Special Topics" },
    { number: 224, title: "I Have Work Enough to Do", category: "Special Topics" },
    { number: 225, title: "We Are Marching On to Glory", category: "Special Topics" },
    { number: 226, title: "Improve the Shining Moments", category: "Special Topics" },
    { number: 227, title: "There Is Sunshine in My Soul Today", category: "Special Topics" },
    { number: 228, title: "You Can Make the Pathway Bright", category: "Special Topics" },
    { number: 229, title: "Today, While the Sun Shines", category: "Special Topics" },
    { number: 230, title: "Scatter Sunshine", category: "Special Topics" },
    { number: 231, title: "Father, Cheer Our Souls Tonight", category: "Special Topics" },
    { number: 232, title: "Let Us Oft Speak Kind Words", category: "Special Topics" },
    { number: 233, title: "Nay, Speak No Ill", category: "Special Topics" },
    { number: 234, title: "Jesus, Mighty King in Zion", category: "Special Topics" },
    { number: 235, title: "Should You Feel Inclined to Censure", category: "Special Topics" },
    { number: 236, title: "Lord, Accept into Thy Kingdom", category: "Special Topics" },
    { number: 237, title: "Do What Is Right", category: "Special Topics" },
    { number: 238, title: "Behold Thy Sons and Daughters, Lord", category: "Special Topics" },
    { number: 239, title: "Choose the Right", category: "Special Topics" },
    { number: 240, title: "Know This, That Every Soul Is Free", category: "Special Topics" },
    { number: 241, title: "Count Your Blessings", category: "Special Topics" },
    { number: 242, title: "Praise God, from Whom All Blessings Flow", category: "Special Topics" },
    { number: 243, title: "Let Us All Press On", category: "Special Topics" },
    { number: 244, title: "Come Along, Come Along", category: "Special Topics" },
    { number: 245, title: "This House We Dedicate to Thee", category: "Special Topics" },
    { number: 246, title: "Onward, Christian Soldiers", category: "Special Topics" },
    { number: 247, title: "We Love Thy House, O God", category: "Special Topics" },
    { number: 248, title: "Up, Awake, Ye Defenders of Zion", category: "Special Topics" },
    { number: 249, title: "Called to Serve", category: "Special Topics" },
    { number: 250, title: "We Are All Enlisted", category: "Special Topics" },
    { number: 251, title: "Behold! A Royal Army", category: "Special Topics" },
    { number: 252, title: "Put Your Shoulder to the Wheel", category: "Special Topics" },
    { number: 253, title: "Like Ten Thousand Legions Marching", category: "Special Topics" },
    { number: 254, title: "True to the Faith", category: "Special Topics" },
    { number: 255, title: "Carry On", category: "Special Topics" },
    { number: 256, title: "As Zion's Youth in Latter Days", category: "Special Topics" },
    { number: 257, title: "Rejoice! A Glorious Sound Is Heard", category: "Special Topics" },
    { number: 258, title: "O Thou Rock of Our Salvation", category: "Special Topics" },
    { number: 259, title: "Hope of Israel", category: "Special Topics" },
    { number: 260, title: "Who's on the Lord's Side?", category: "Special Topics" },
    { number: 261, title: "Thy Servants Are Prepared", category: "Special Topics" },
    { number: 262, title: "Go, Ye Messengers of Glory", category: "Special Topics" },
    { number: 263, title: "Go Forth with Faith", category: "Special Topics" },
    { number: 264, title: "Hark, All Ye Nations!", category: "Special Topics" },
    { number: 265, title: "Arise, O God, and Shine", category: "Special Topics" },
    { number: 266, title: "The Time Is Far Spent", category: "Special Topics" },
    { number: 267, title: "How Wondrous and Great", category: "Special Topics" },
    { number: 268, title: "Come, All Whose Souls Are Lighted", category: "Special Topics" },
    { number: 269, title: "Jehovah, Lord of Heaven and Earth", category: "Special Topics" },
    { number: 270, title: "I'll Go Where You Want Me to Go", category: "Special Topics" },
    { number: 271, title: "Oh, Holy Words of Truth and Love", category: "Special Topics" },
    { number: 272, title: "Oh Say, What Is Truth?", category: "Special Topics" },
    { number: 273, title: "Truth Reflects upon Our Senses", category: "Special Topics" },
    { number: 274, title: "The Iron Rod", category: "Special Topics" },
    { number: 275, title: "Men Are That They Might Have Joy", category: "Special Topics" },
    { number: 276, title: "Come Away to the Sunday School", category: "Special Topics" },
    { number: 277, title: "As I Search the Holy Scriptures", category: "Special Topics" },
    { number: 278, title: "Thanks for the Sabbath School", category: "Special Topics" },
    { number: 279, title: "Thy Holy Word", category: "Special Topics" },
    { number: 280, title: "Welcome, Welcome, Sabbath Morning", category: "Special Topics" },
    { number: 281, title: "Help Me Teach with Inspiration", category: "Special Topics" },
    { number: 282, title: "We Meet Again in Sabbath School", category: "Special Topics" },
    { number: 283, title: "The Glorious Gospel Light Has Shone", category: "Special Topics" },
    { number: 284, title: "If You Could Hie to Kolob", category: "Special Topics" },
    { number: 285, title: "God Moves in a Mysterious Way", category: "Special Topics" },
    { number: 286, title: "Oh, What Songs of the Heart", category: "Special Topics" },
    { number: 287, title: "Rise, Ye Saints, and Temples Enter", category: "Special Topics" },
    { number: 288, title: "How Beautiful Thy Temples, Lord", category: "Special Topics" },
    { number: 289, title: "Holy Temples on Mount Zion", category: "Special Topics" },
    { number: 290, title: "Rejoice, Ye Saints of Latter Days", category: "Special Topics" },
    { number: 291, title: "Turn Your Hearts", category: "Special Topics" },
    { number: 292, title: "O My Father", category: "Special Topics" },
    { number: 293, title: "Each Life That Touches Ours for Good", category: "Special Topics" },
    { number: 294, title: "Love at Home", category: "Special Topics" },
    { number: 295, title: "O Love That Glorifies the Son", category: "Special Topics" },
    { number: 296, title: "Our Father, by Whose Name", category: "Special Topics" },
    { number: 297, title: "From Homes of Saints Glad Songs Arise", category: "Special Topics" },
    { number: 298, title: "Home Can Be a Heaven on Earth", category: "Special Topics" },

    // Children's Songs
    { number: 299, title: "Children of Our Heavenly Father", category: "Children's Songs" },
    { number: 300, title: "Families Can Be Together Forever", category: "Children's Songs" },
    { number: 301, title: "I Am a Child of God", category: "Children's Songs" },
    { number: 302, title: "I Know My Father Lives", category: "Children's Songs" },
    { number: 303, title: "Keep the Commandments", category: "Children's Songs" },
    { number: 304, title: "Teach Me to Walk in the Light", category: "Children's Songs" },
    { number: 305, title: "The Light Divine", category: "Children's Songs" },
    { number: 306, title: "God's Daily Care", category: "Children's Songs" },
    { number: 307, title: "In Our Lovely Deseret", category: "Children's Songs" },
    { number: 308, title: "Love One Another", category: "Children's Songs" },

    // For Women
    { number: 309, title: "As Sisters in Zion (Women)", category: "For Women" },
    { number: 310, title: "A Key Was Turned in Latter Days (Women)", category: "For Women" },
    { number: 311, title: "We Meet Again as Sisters (Women)", category: "For Women" },
    { number: 312, title: "We Ever Pray for Thee (Women)", category: "For Women" },
    { number: 313, title: "God Is Love (Women)", category: "For Women" },
    { number: 314, title: "How Gentle God's Commands (Women)", category: "For Women" },
    { number: 315, title: "Jesus, the Very Thought of Thee (Women)", category: "For Women" },
    { number: 316, title: "The Lord Is My Shepherd (Women)", category: "For Women" },
    { number: 317, title: "Sweet Is the Work (Women)", category: "For Women" },
    { number: 318, title: "Love at Home (Women)", category: "For Women" },

    // For Men
    { number: 319, title: "Ye Elders of Israel (Men)", category: "For Men" },
    { number: 320, title: "The Priesthood of Our Lord (Men)", category: "For Men" },
    { number: 321, title: "Ye Who Are Called to Labor (Men)", category: "For Men" },
    { number: 322, title: "Come, All Ye Sons of God (Men)", category: "For Men" },
    { number: 323, title: "Rise Up, O Men of God (Men's Choir)", category: "For Men" },
    { number: 324, title: "Rise Up, O Men of God (Men)", category: "For Men" },
    { number: 325, title: "See the Mighty Priesthood Gathered (Men's Choir)", category: "For Men" },
    { number: 326, title: "Come, Come, Ye Saints (Men's Choir)", category: "For Men" },
    { number: 327, title: "Go, Ye Messengers of Heaven (Men's Choir)", category: "For Men" },
    { number: 328, title: "An Angel from on High (Men's Choir)", category: "For Men" },
    { number: 329, title: "Thy Servants Are Prepared (Men's Choir)", category: "For Men" },
    { number: 330, title: "See, the Mighty Angel Flying (Men's Choir)", category: "For Men" },
    { number: 331, title: "Oh Say, What Is Truth? (Men's Choir)", category: "For Men" },
    { number: 332, title: "Come, O Thou King of Kings (Men's Choir)", category: "For Men" },
    { number: 333, title: "High on the Mountain Top (Men's Choir)", category: "For Men" },
    { number: 334, title: "I Need Thee Every Hour (Men's Choir)", category: "For Men" },
    { number: 335, title: "Brightly Beams Our Father's Mercy (Men's Choir)", category: "For Men" },
    { number: 336, title: "School Thy Feelings (Men's Choir)", category: "For Men" },
    { number: 337, title: "O Home Beloved (Men's Choir)", category: "For Men" },

    // Patriotic
    { number: 338, title: "America the Beautiful", category: "Patriotic" },
    { number: 339, title: "My Country, 'Tis of Thee", category: "Patriotic" },
    { number: 340, title: "The Star-Spangled Banner", category: "Patriotic" },
    { number: 341, title: "God Save the King", category: "Patriotic" }
];

async function populateHymns() {
    try {
        await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/your-database');
        console.log('Connected to MongoDB');

        // Clear existing hymns
        await Hymn.deleteMany({});
        console.log('Cleared existing hymns');

        // Insert all hymns
        await Hymn.insertMany(hymns);
        console.log(`Inserted ${hymns.length} hymns successfully`);

        await mongoose.disconnect();
        console.log('Disconnected from MongoDB');
    } catch (error) {
        console.error('Error populating hymns:', error);
        process.exit(1);
    }
}

populateHymns();
